### PR TITLE
Tahmina

### PR DESCRIPTION
**Pull request by TahminaZ**
kindly review my FINRA method

### CODE REVIEW

**Comment by TahminaZ** [comment]
for your review

**Review by ValeriySyutkin — COMMENTED** [review]
All looks great except that you should've make it in a separate method  instead of in the body of the main method

**Review by TahminaZ — COMMENTED** [review]
made changes as requested

**Review by ValeriySyutkin — COMMENTED** [review]
Better. I actually have not even noticed "AR" instead of "RA" at first.
But still try to do method in a class as a separate method instead of inside of the main method :)

**Comment by TahminaZ** [comment]
updated

**Review by alinazar77 — APPROVED** [review]

**Pull request merged**
